<a href="https://colab.research.google.com/github/hrxhit2214/data-science/blob/main/pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:


# import Package
import pandas as pd
import numpy as np
pd.__version__



number_series = pd.Series([1, 2, 3, 4, 5])
print(number_series)



number_series= pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'],name='Number')
print(number_series)


print(number_series[0])
print(number_series['a'])
print(number_series[0])

some_2D_array = np.random.randint(4,7,(7, 5))
print(some_2D_array)


first_dataframe = pd.DataFrame(some_2D_array, columns=['Akshay', 'Devashish', 'Divy', 'Monika','Kaushik'])
print(first_dataframe)



0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
Name: Number, dtype: int64
1
1
1
[[5 4 6 6 6]
 [6 6 6 5 6]
 [4 5 4 5 4]
 [4 6 6 4 5]
 [6 5 5 5 4]
 [4 4 5 5 4]
 [5 6 4 5 4]]
   Akshay  Devashish  Divy  Monika  Kaushik
0       5          4     6       6        6
1       6          6     6       5        6
2       4          5     4       5        4
3       4          6     6       4        5
4       6          5     5       5        4
5       4          4     5       5        4
6       5          6     4       5        4


<ipython-input-2-b0f86d9813a3>:17: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(number_series[0])
<ipython-input-2-b0f86d9813a3>:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(number_series[0])
